#!/bin/csh -f
#
#
# This program makes 
#
# Getting Lexical Patterns 
#
if ($#argv == 0) then       # if no argument
   echo "This program is for getting Lexical Patterns from corpus"
   echo "Usage : GetLEXFEATURE CORPUS LEXFEATURE"
   exit 1
endif
#
#
echo 'Getting Lexical Features from CORPUS'
./getonepttn $1 >! $1.t1
echo 'DONE....'
#
# $1.t1 is Pttn
#
echo 'Sorting Tag-Sequence'
sort $1.t1 >! $1.t1.sort
echo 'DONE....'
/bin/rm $1.t1
#
#
echo 'Counting Frequencies of Tag-Sequence'
freq < $1.t1.sort >! $2
/bin/rm $1.t1.sort
echo 'DONE....'
#
#
#

