#!/bin/csh -f
#
#
# This program makes 
#     1. `Dictionary with prob' 
#     2. `Connectability Matrix'
#
#                        From CORPUS
#
setenv TOPDIR "."
if ($#argv == 0) then       # if no argument
   echo "This program getting informations from corpus"
   echo " 1. Dictionary with probabilities , irr-codes"
   echo " 2. Connectability Matrix based on corpus"
   echo "Usage : corpus2info CORPUS [DICT] [CNMTRX]"
   echo "Corpus를 이용하여 DICT와 Connectability Matrix를 만든다"
   exit 1
endif
#
# Part 1.
#
echo '================================='
echo ' 1. Making Dictionary with prob  '
echo '================================='
#
$TOPDIR/MKDctFrmCrps $1 $2
# 
echo '================================='
echo '              End                '
echo '================================='
#
# Part 2.
#
echo '================================='
echo ' 2. Making Connectability Matrix '
echo '================================='
#
$TOPDIR/MKCnFrmCrps $1 $3
# 
echo '================================='
echo '              End                '
echo '================================='
#
#
